#!/bin/bash
set -e

cd $(dirname $0)/..

echo "Running golang tests..."

# Run unit tests (excluding integration tests)
# Integration tests require network access and must be run separately via:
#   ./scripts/test-integration
#   make test-integration
go test -cover -tags=test ./...
