name: Team ORBS Chart Tools CI

on:
  workflow_call:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'

permissions:
  contents: read

env:
  CI: true

jobs:
  build:
    name : Build, test  & validate
    runs-on : ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/go1.26
    strategy:
      matrix:
          include:
            - platform: linux/amd64
            - platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup go workspace
        run: go work init . ./helmtools
      - name : CI
        run : make ci
